stages:
  - test_in_oraclejdk8
  - name: test_in_oraclejdk9
    if: branch = master
  - name: deploy
    if: tag =~ ^v0\.

jobs:
  include:
  - stage: test_in_oraclejdk8
    language: java
    jdk: oraclejdk8
    script:
    - travis_wait 60 ./gradlew check

  - stage: test_in_oraclejdk9
    language: java
    jdk: oraclejdk9
    script:
    - travis_wait 60 ./gradlew check

  - stage: deploy
    language: python
    python: 3.6
    before_install:
    - cd docs
    script:
    - make html
    before_deploy:
    - sphinx-versioning build docs build/html -r v0.511 -w "nobranch"
    - touch build/html/.nojekyll
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: ${GITHUB_TOKEN}
      keep-history: true
      repo: knewjade/sfinder-manual
      local-dir: docs/build/html/
      target-branch: master
