stages:
  - name: test_in_oraclejdk11
  - name: deploy
    if: tag =~ ^v0\.

jobs:
  include:
  - stage: test_in_oraclejdk11
    language: java
    jdk: oraclejdk11
    script:
    - travis_wait 45 ./gradlew check

  - stage: deploy
    language: python
    python: 3.8
    before_install:
    - cd docs
    script:
    - make html
    before_deploy:
    - touch build/html/.nojekyll
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: ${GITHUB_TOKEN}
      keep-history: true
      repo: knewjade/sfinder-manual
      local-dir: docs/build/html/
      target-branch: master
