branches:
  except:
  - latest
matrix:
  include:
  - language: java
    jdk: oraclejdk8
    script:
    - travis_wait 20 ./gradlew check

  - language: python
    python: 3.6
    before_install:
    - cd docs
    script:
    - make html
    before_deploy:
    - export TAG_SHA=`git log --source master -n 1 --format=%H`
    - "curl -H \"Authorization: token $GITHUB_TOKEN\" -X PATCH https://api.github.com/repos/knewjade/solution-finder/git/refs/tags/edge --data \"{\\\"sha\\\":\\\"$TAG_SHA\\\", \\\"force\\\":true}\""
    - sphinx-versioning build docs build/html -r latest -w "nobranch"
    - touch build/html/.nojekyll
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: ${GITHUB_TOKEN}
      keep-history: true
      repo: knewjade/sfinder-manual
      local-dir: build/html/
      target-branch: master
