matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - travis_wait 20 ./gradlew check

    - language: python
      python: 3.6
      before_install:
        - cd docs
      script:
        - make html
      before_deploy:
        - git tag --force latest `git log --source master -n 1 --format=%H`
        - git push --force deploy latest
        - sphinx-versioning build docs build/html -r latest -w "nobranch"
        - touch build/html/.nojekyll
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: ${GITHUB_TOKEN}
        keep-history: true
        repo: knewjade/sfinder-manual
        local-dir: build/html/
        target-branch: master
