matrix:
  include:
    - language: java
      jdk: oraclejdk8
      script:
        - travis_wait 20 ./gradlew check

    - language: python
      python: 3.6
      before_install:
        - cd docs
      script:
        - make html
      before_deploy:
        - sphinx-versioning build docs build/html -r latest -w "nobranch"
        - touch build/html/.nojekyll
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: ${GITHUB_TOKEN}
        keep-history: true
        repo: knewjade/sfinder-manual
        local-dir: build/html/
        target-branch: master

# to see: https://docs.travis-ci.com/user/deployment/custom/
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git checkout master
  - git tag --force latest
  - git push --force deploy latest
