name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew check
        env:
          ALLOWS_ALL_TEST: ${{ github.ref == 'refs/heads/main' }}
          JAVA_OPTS: -Xms2048M -Xmx2048M